version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    target-branch: main
  - package-ecosystem: npm
    directory: "/packages/core/"
    schedule:
      interval: weekly
    target-branch: main
  - package-ecosystem: npm
    directory: "/packages/ui/"
    schedule:
      interval: weekly
    target-branch: main
  - package-ecosystem: npm
    directory: "/packages/react/"
    schedule:
      interval: weekly
    target-branch: main
  - package-ecosystem: npm
    directory: "/packages/ngx/"
    schedule:
      interval: weekly
    target-branch: main
  - package-ecosystem: npm
    directory: "/packages/svelte/"
    schedule:
      interval: weekly
    target-branch: main
  - package-ecosystem: npm
    directory: "/packages/socketio-client/"
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "@types/socket.io-client"
      - dependency-name: "socket.io-client"
    target-branch: main
  - package-ecosystem: npm
    directory: "/testapps/ngx"
    schedule:
      interval: weekly
    target-branch: main
  - package-ecosystem: npm
    directory: "/testapps/core"
    schedule:
      interval: weekly
    target-branch: main
  - package-ecosystem: npm
    directory: "/testapps/svelte"
    schedule:
      interval: weekly
    target-branch: main
  - package-ecosystem: npm
    directory: "/testapps/react"
    schedule:
      interval: weekly
    target-branch: main
    ignore:
      - dependency-name: "react"
      - dependency-name: "react-dom"
