import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import { T, Tolgee, TolgeeProvider } from '@tolgee/react';
import { InContextTools } from '@tolgee/web/tools';
import { useRouter } from 'next/router';

import enLocale from '../i18n/en.json';
import deLocale from '../i18n/de.json';
import styles from '../styles/Home.module.css';
import LocaleSwitcher from '../component/LanguageSwitcher';

const tolgee = Tolgee()
  .use(InContextTools())
  .init({
    apiKey: process.env.NEXT_PUBLIC_TOLGEE_API_KEY,
    apiUrl: process.env.NEXT_PUBLIC_TOLGEE_API_URL,
    staticData: {
      en: enLocale,
      de: deLocale,
    },
  });

const Home: NextPage = () => {
  const router = useRouter();

  const [ready, setReady] = useState(false);

  useEffect(() => {
    const queryParams = new URLSearchParams(window.location.search);
    const apiKey =
      queryParams.get('api_key') || process.env.NEXT_PUBLIC_TOLGEE_API_KEY;

    tolgee.updateOptions({ apiKey });
    setReady(true);
  }, []);

  return ready ? (
    <TolgeeProvider tolgee={tolgee} language={router.locale}>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <LocaleSwitcher />

        <main className={styles.main}>
          <h1>
            <T keyName="app-title" />
          </h1>
        </main>
      </div>
    </TolgeeProvider>
  ) : null;
};

export default Home;
