import type { NextPage } from 'next';
import Head from 'next/head';
import { T } from '@tolgee/react';
import UI from '@tolgee/ui';
import enLocale from '../i18n/en.json';
import deLocale from '../i18n/de.json';
import { useRouter } from 'next/router';
import { TolgeeProvider } from '@tolgee/react';

import styles from '../styles/Home.module.css';
import LocaleSwitcher from '../component/LanguageSwitcher';

const Home: NextPage = () => {
  const { locale: activeLocale } = useRouter();

  const router = useRouter();

  return router.isReady ? (
    <TolgeeProvider
      ui={UI}
      forceLanguage={activeLocale}
      apiKey={
        (router.query.api_key as string) ||
        process.env.NEXT_PUBLIC_TOLGEE_API_KEY
      }
      apiUrl={process.env.NEXT_PUBLIC_TOLGEE_API_URL}
      staticData={{
        en: enLocale,
        de: deLocale,
      }}
    >
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <LocaleSwitcher />

        <main className={styles.main}>
          <h1>
            <T>on-the-road-title</T>
          </h1>
        </main>
      </div>
    </TolgeeProvider>
  ) : null;
};

export default Home;
