pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot\[bot\]$
      - check-success=Test
      - title~=Bump [^\s]+ from ([\d]+)\..+ to \1\.
    actions:
      merge:
        method: rebase