name: Automerge Deps!

on:
  workflow_run:
    types:
      - completed
    workflows:
      - 'Test'

jobs:
  merge-me:
    name: Merge it!
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.event.workflow_run.conclusion == 'success' }}
        name: Merge it!
        uses: ridedott/merge-me-action@v2
        with:
          PRESET: DEPENDABOT_MINOR
          GITHUB_TOKEN: '${{ secrets.TOLGEE_MACHINE_PAT }}'
