name: Dependabot Auto-Merge

on: [ pull_request_target ]

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]'  }}
    steps:
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{ secrets.TOLGEE_MACHINE_PAT }}
      - name: Merge PR
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.TOLGEE_MACHINE_PAT }}
          script: |
            const pr = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });
            if (!pr.data.title.startsWith('chore(deps):')) {
              console.log('Not Merged 🚫');
              console.log(`Title '${pr.data.title}' does not start with 'chore(deps):'`);
            } else if (pr.data.user.login !== 'dependabot[bot]') {
              console.log('Not Merged 🚫');
              console.log(`User '${pr.data.user.login}' does not equal 'dependabot[bot]'`);
            } else {
              await github.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
              });
              console.log('Merged 🎉');
            }
